/*
    Closures are represented by traits, so we can't return them directly
    We state the function type (Fn, FnOnce, FnMut) & do the similar syntax we did for functions

    Reminder: WHen compiled, each closure becomes its own unique type that's generated by the compiler called opaque types, even if closures have the same signature
        - Eachh opaque type is unique
        - Similar to how Rust produces different concrete types for distinct async blocks even w/ same output type
        - We use `impl Trait` (for one opaque closure type per function), or
        - We use trait objects (`Box<dyn Fn>`), which allow us to return different types implementing the same trait
*/

fn main() {
    /*
        If we try running this, we get an error
        When we return an impl Trait, we get a unique opaque type; where we can't see the details that Rust creates

        let handlers = vec![og_returns_closure(), og_returns_initialized_closure(123)];
        for handler in handlers {
            let output = handler(5);
            println!("{output}");
        }
    */

    // We can use trait objects to get past this like we've done before
    let handlers = vec![returns_closure(), returns_initialized_closure(123)];
    for handler in handlers {
        let output = handler(5);
        println!("{output}");
    }
}

fn returns_closure() -> Box<dyn Fn(i32) -> i32> {
    Box::new(|x| x + 1)
}

fn returns_initialized_closure(init: i32) -> Box<dyn Fn(i32) -> i32> {
    Box::new(move |x| x + init)
}

fn og_returns_closure() -> impl Fn(i32) -> i32 {
    |x| x + 1
}

fn og_returns_initialized_closure(init: i32) -> impl Fn(i32) -> i32 {
    move |x| x + init
}